### ISSUE TITLE
大佬下面两个错误是什么原因导致的？麻烦解答一下

### ISSUE THREAD

**Issue by BirderEric** [Jittor/TrafficSignDetection#1]
Traceback (most recent call last):
  File "train.py", line 123, in <module>
    main()
  File "train.py", line 118, in main
    train()
  File "train.py", line 77, in train
    faster_rcnn = FasterRCNN(n_class = len(CLASSNAMES)+1)
  File "/home/TrafficSignDetection-master/model/faster_rcnn.py", line 38, in __init__
    self.backbone = Resnet50(pretrained=True)
  File "/home/TrafficSignDetection-master/model/resnet.py", line 112, in Resnet50
    if pretrained: model.load("jittorhub://resnet50.pkl")
  File "/usr/local/lib/python3.7/dist-packages/jittor/__init__.py", line 646, in load
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'jittorhub://resnet50.pkl'
_______________________________________________________________________________
Traceback (most recent call last):
  File "train.py", line 123, in <module>
    main()
  File "train.py", line 118, in main
    train()
  File "train.py", line 87, in train
    rpn_loc_loss,rpn_cls_loss,roi_loc_loss,roi_cls_loss,total_loss = faster_rcnn(images,boxes,labels)
  File "/usr/local/lib/python3.7/dist-packages/jittor/__init__.py", line 458, in __call__
    return self.execute(*args, **kw)
  File "/home/TrafficSignDetection-master/model/faster_rcnn.py", line 81, in execute
    return self._forward_train(features,img_size,boxes,labels)
  File "/home/TrafficSignDetection-master/model/faster_rcnn.py", line 87, in _forward_train
    rpn_locs, rpn_scores, rois, roi_indices, anchor = self.rpn(features, img_size)
  File "/usr/local/lib/python3.7/dist-packages/jittor/__init__.py", line 458, in __call__
    return self.execute(*args, **kw)
  File "/home/TrafficSignDetection-master/model/rpn.py", line 461, in execute
    batch_index = i * jt.ones((len(roi),), dtype='int32')
TypeError: object of type 'jittor_core.Var' has no len()

**Comment by li-xl** [comment]
感觉像是没有升级jittor最新版导致的，请问您的jittor版本是多少
